 //http://www.jokes4us.com/
export default {
1:'What do you know when people start calling you broccoli? You\'re having a bad hair day.',
2:'Broccoli: I look like a tree. Walnut: I look like a brain. Mushroom: I look like an umbrella. Banana: Dude! Change the topic.',
3:'Why didn\'t the coconuts go to the ballet? They were afraid of the nutcracker.',
4:'Q: What is best Beatles song? A: Latte Be!',
5:'Q: What do you call sad coffee? A: Despresso.',
6:'Q: What kind of coffee was served on the Titanic? A: Sanka.',
7:'What day do eggs hate most? Fry-day!',
8:'What does the chicken say to get across a busy street? EGGS-cuse me please!',
9:'What did lemon say to lime? Nothing, stupid, lemons don\'t talk.',
10:'Take life with a grain of salt, a slice of lemon, and a shot of tequila.',
11:'Q: What do you call a hobbit with a healthy appetite? A: Lord of the Onion Rings.',
12:'Q: Why do they call it Fast Food? A: Because if you dont eat it really fast, you might actually taste it.',
13:'Someone who eats spinach leaves must like them a whole bunch.',
14:'What did the young pancake say to the old burnt pancake? I don\'t like your flip side.',
15:'Have you heard of the garlic diet? You don\'t lose much weight, but from a distance your friends think you look thinner! ',
16:'How should you live your life? By seasoning the moment.',
17:'How do you know you in "love" with spicy food? After getting to third basil. ',
18:'A guy walks into the doctor\'s office. A cayenne pepper stuck in one of his ears, a ginger root in the other ear, and a jalapeno stuck in one nostril. <br/>The man says, "Doc, this is terrible. What\'s wrong with me?" <br/>The doctor says, "Well, first of all, you need to eat more sensibly."',
19:'Q: What would happen if pigs could fly? A: The price of pork would go skyrocket.',
20:'Do you want to hear a dirty joke? A pig fell in the mud. <br/>Do you want to hear a clean joke? A pig took a bath. ',
21:'Q: Why do potatoes make good detectives? A: Because they keep their eyes peeled. ',
22:'Q: What do you call a baby potato? A: A small fry! ',
23:'Q: "Waiter, will my pizza be long?" A: "No sir, it will be round!" ',
24:'Q: What did the pepperoni say to the cook? A: You wanna pizza me? ',
25:'7 days without pizza makes one weak.',
26:'Q: What do you get if you divide the circumference of a pumpkin by its diameter? A: Pumpkin pi.',
27:'What do you call a sad raspberry? A blueberry.',
28:'Two girls: "A tray of sushi, please." Waiter: "To eat or to post photos of on Instagram?',
29:'What did the sushi say to the bee? Wassabee!',
30:'Q: What\'s yellow and always points to the north? A: A magnetic banana.',
31:'Q: What kind of a key opens a banana? A: A monkey!',
32:''
}
